apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-deployment
  namespace: app
  labels:
    app: logger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger
        image: public.ecr.aws/c6w3t1p6/aicloudops-logger:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 800m
            memory: 1Gi
        env:
        - name: RABBITMQ_HOST
          valueFrom:
            secretKeyRef:
              name: rabbitmq-cluster-default-user
              key: host
        - name: RABBITMQ_PORT
          valueFrom:
            secretKeyRef:
              name: rabbitmq-cluster-default-user
              key: port
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-cluster-default-user
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-cluster-default-user
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-cluster-pguser-logger-app
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-cluster-pguser-logger-app
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pg-cluster-pguser-logger-app
              key: dbname
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: pg-cluster-pguser-logger-app
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: pg-cluster-pguser-logger-app
              key: port
        volumeMounts:
        - name: code-files
          mountPath: /tmp
      volumes:
      - name: code-files
        persistentVolumeClaim:
          claimName: ai-code-pvc




