apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-code-pv
  namespace: app
  labels:
    type: local
spec:
  storageClassName: standard # use default storage class from minikube, would use cloud storage in bigger app
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/tmp/ai-code"
