apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-code-pvc
  namespace: app
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      type: local
