apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
  namespace: app
  labels:
    app: chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      serviceAccountName: chatbot-service-account
      containers:
      - name: chatbot
        image: 'public.ecr.aws/c6w3t1p6/aicloudops-chatbot:latest'
        stdin: true
        tty: true
        ports:
        - containerPort: 7681
        resources:
          requests:
            memory: 64Mi
            cpu: 250m
          limits:
            memory: 128Mi
            cpu: 500m
        env:
        - name: RABBITMQ_HOST
          valueFrom:
            secretKeyRef:
              name: rabbitmq-cluster-default-user
              key: host
        - name: RABBITMQ_PORT
          valueFrom:
            secretKeyRef:
              name: rabbitmq-cluster-default-user
              key: port
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-cluster-default-user
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-cluster-default-user
              key: password
        - name: VOLUME_NAME
          value: ai_code
        - name: OPENAI_MODEL
          valueFrom:
            secretKeyRef:
              name: chatbot-env
              key: OPENAI_MODEL
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: chatbot-env
              key: OPENAI_API_KEY
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: chatbot-env
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: chatbot-env
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: chatbot-env
              key: AWS_DEFAULT_REGION
        - name: RUNNING_IN
          value: "k8s"
        volumeMounts:
        - name: code-files
          mountPath: /tmp
      volumes:
      - name: code-files
        persistentVolumeClaim:
          claimName: ai-code-pvc
