ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  pathtype: ImplementationSpecific
  hosts:
  - host: localhost
    paths:
    - path: /kibana(/|$)(.*)


kibanaConfig:
  kibana.yml: |
    server.basePath: "/kibana"
    server.publicBaseUrl: "http://localhost/kibana"
