logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false

logstashPipeline:
  logstash.conf: |
    input {
      beats {
        port => 5044
        ecs_compatibility => v1
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-master:9200"]
        ecs_compatibility => v1
      }
    }

logstashJavaOpts: "-Xmx256m -Xms256m"

service:
  annotations: {}
  type: ClusterIP
  loadBalancerIP: ""
  ports:
  - name: beats
    port: 5044
    protocol: TCP
    targetPort: 5044
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "1536Mi"
  limits:
    cpu: "1000m"
    memory: "1536Mi"

