controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus
  podAnnotations:
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
# controller:
#   hostAliases:
#   - ip: "192.168.1.1"
#     hostnames:
#     - "www.example.com"
#     - "foo.bar"


