apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-proxy
  labels:
    app: docker-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-proxy
  template:
    metadata:
      labels:
        app: docker-proxy
    spec:
      containers:
      - name: docker-proxy
        image: tecnativa/docker-socket-proxy
        ports:
        - containerPort: 2375
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "0.5"
            memory: "250Mi"
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        env:
        - name: BUILD
          value: "1"
        - name: IMAGES
          value: "1"
        - name: CONTAINERS
          value: "1"
        - name: VOLUMES
          value: "1"
        - name: NETWORKS
          value: "1"
        - name: POST
          value: "1"
        - name: EXEC
          value: "1"
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket