apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: app
spec:
  replicas: 3
  resources:
    requests:
      cpu: 400m
      memory: 1Gi
    limits:
      cpu: 800m
      memory: 1Gi
