apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  labels:
    app: chatbot
spec:
  ports:
  - port: 8080 # service port
    targetPort: 7681 # container port 
    protocol: TCP
    name: http
  selector:
    app: chatbot