apiVersion: v1
kind: Service
metadata:
  name: logger-service
spec:
  selector:
    app: logger
  ports:
  - protocol: TCP
    port: 80 # The service port
    targetPort: 80 # The container port
  type: ClusterIP
