apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: amqp
    name: amqp
  - port: 15672
    targetPort: management
    name: management
  selector:
    app: rabbitmq
  type: ClusterIP