name: AICloudOps - CI

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - aicloudops/chatbot/**
    - aicloudops/logger/**
  pull_request:
    branches:
    - main
    paths:
    - aicloudops/chatbot/**
    - aicloudops/logger/**

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      microservices: ${{ steps.filter.outputs.changes }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Detect Changes
      uses: dorny/paths-filter@v3
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          chatbot: aicloudops/chatbot/**
          logger: aicloudops/logger/**

    # upload artifact to be used by the CD workflow
    - name: Output Changes to JSON File
      run: |
        echo "${{ steps.filter.outputs.changes }}" > changes.json

    - name: Upload Changes to Artifact
      uses: actions/upload-artifact@v4
      with:
        name: aicloudops-detected-changes-${{ github.sha }}
        path: changes.json

  lint-test:
    name: Lint - Test
    runs-on: ubuntu-latest
    # needs: [detect-changes]
    # strategy:
    #   matrix:
    #     microservice: ${{ fromJSON(needs.detect-changes.outputs.microservices) }}
    # defaults:
    #   run:
    #     working-directory: ./aicloudops/${{ matrix.microservice }}

    steps:
    # - name: Checkout
    #   uses: actions/checkout@v4

    - name: Test ls
      run: |
        ls -la
        pwd


